osx_image: xcode11.3
language: swift

env:
  global:
    - LANG=en_US.UTF-8

cache:
  - bundler

before_install:
  - brew update

script:
  - rake test

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash)